### PR TITLE
Adds an optional TLS check for SimpleMatcher.

### PR DESCRIPTION
**Pull request by grahammiln**
A TLS check is needed for protocol handlers that **must** be secured.

When serve2 detects and passes on a secure connection to an http handler, the TLS information is effectively lost. The http server is not aware of the TLS outer connection and thus does not patch up `http.Request.TLS` fields in incoming requests.

With `http.Request.TLS` always unset, http middleware and http handlers are unable to determine if the request is secure.

Ideally, we would find a way to patch up the lost `http.Request.TLS` but this did not appear trivial.

Instead this minor modification to `SimpleMatcher` provides a reasonable assurance of TLS before the handler gets the connection.
## Serving HTTP and HTTPS

With this change, serve2 can be used to serve both `http` and `https` content from the same port.

The code example below creates a serve2 instance that will serve different content depending on the `http` or `https` scheme used:

```
 server := serve2.New()

 http := proto.NewHTTP(securedRouter)
 https := NewHTTPS(router)

 tls, err := proto.NewTLS([]string{"http"}, aCertificateFilePath, aTLSKeyFilePath)
 if err != nil {
     log.Fatalf("[ERROR] Listen to '%v' failed : ", config.Listen, err)
 }
 server.AddHandlers(tls, http, https)
```

I have chosen not to include `NewHTTPS` in this pull request. The comments above `NewHTTP` hint the code this is based on, `NewHTTP`, is not best practice or at least likely to be superseded in the near future.

`NewHTTPS` is implemented in full below:

```
func NewHTTPS(handler http.Handler) *proto.ListenProxy {
    sm := &proto.SimpleMatcher{Matches: proto.HTTPMethods, RequiresTLS: true}
    lp := proto.NewListenProxy(sm.Check, 10)
    lp.Description = "HTTPS"

    httpServer := http.Server{Addr: ":https", Handler: handler}
    go httpServer.Serve(lp.Listener())
    return lp
}
```

### CODE REVIEW

**Comment by joushou** [comment]
I definitely agree that being able to set http.Request.TLS would be nice, but as you have noticed, it's a bit tricky. I would in general like for the http library to have much more functionality exported...

Before we continue with this specific PR, are you sure that TLSMatcher wasn't what you wanted to use, which is capable of detecting a TLS connection and checking the requested protocol? Something like:

```go
func NewHTTPS(handler http.Handler) *ListenProxy {
	tm := &proto.TLSMatcher{
		NegotiatedProtocols: []string{"http/1.1"},
		Checks: proto.TLSCheckNegotiatedProtocol,
	}
	lp := NewListenProxy(tm.Check, 10)
	lp.Description = "HTTPS"

	httpServer := http.Server{Addr: ":https", Handler: handler}
	go httpServer.Serve(lp.Listener())
	return lp
}
```

As a side-note, I believe that HTTP/1.1 is advertised as "http/1.1" normally, not "http", as you wrote in your example.

**Comment by grahammiln** [comment]
I have a couple of protocols behind TLS – one is `http` and the other is a custom protocol that also uses TLS.

I have a modified SimpleMatcher implementation that works but it requires more code than is ideal.

After experimenting, the resulting PR felt like the smallest change for the largest return. :-)

**Comment by joushou** [comment]
TLS provides a protocol negotiation mechanism, which allows you to tell which specific protocol you want "next" (hence the name "NextProtos"). Browsers use this to request HTTP/1.1 or HTTP/2 using different "NextProto" requests.

If using NextProto (NegotiatedProtocol in Golang-speak) is insufficient, and the protocol can *only* be detected by reading the first few bytes, then something like the modified simplematcher would be required. I'm not sure if I would personally put it straight into the SimpleMatcher, though, as it was... Well, supposed to be simple.

I have an idea that might simplify something like this in the future, though... What if we had a "ChainMatcher", where you could do something like:
```go
t := proto.TLSMatcher{}
h := proto.NewHTTP(secureRouter)
ch := proto.NewChainMatcher(h.Handle, t.Check, h.Check)

server.AddHandler(ch)
```

Does that idea sound bad? That way, you can have SimpleMatcher be simple (In the sense that it doesn't have very specific "extra" functionality), but then *also* require TLSMatcher's check to validate before calling the supplied handler. It should also be very fast for me to implement, while being considerably more flexible. An empty TLSMatcher should just match any TLS connection. I would still suggest adding the NegotiatedProtocol check if you can, though.

**Comment by grahammiln** [comment]
Thank you for the insight into `TLSMatcher` and `NegotiatedProtocol`.

A chained match approach would be better than this PR.

I wish more SSL/TLS libraries and tools provide easy access to `NextProto`. :-)

**Comment by joushou** [comment]
Which TLS library are you using? ALPN ("Application-Level Protocol Negotiation", or "Next Protocol Negotiation" in earlier versions. Yes, I googled the proper name, sue me!) is a relatively new extension, introduced for the purpose of distinguishing between HTTP/1.1 and HTTP/2, but universal so it can be used to request any protocol. Chrome introduced it around 2012. GnuTLS had support for it since 2013, although (libre|open)ssl didn't add support till January this year...

Anyway, the branch "test" includes a ChainMatcher with tests that pass, but it doesn't have examples, comments, or anything like that yet. I'll get that done later today. Feel free to comment on it.

**Comment by grahammiln** [comment]
I am investigating if [serve2](https://github.com/joushou/serve2) could help with existing OS X and iOS based clients and services. They use a mix of networking technologies including Apple's CFSockets – so are limited by Apple's historic choices and exposed APIs.

It would be great to have everyone running the latest versions but that is not in my control. :-)

Thank you for sharing serve2 and entertaining this esoteric pull request. I will close #5 and keep an eye on `ChainMatcher`.

**Comment by joushou** [comment]
"Chain" added to master. The example just so happens to be a HTTP + TLSMatcher one.

**Pull request closed without merging**
